# This is a basic workflow to help you get started with Actions

name: Build LaTeX doc
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repo
        uses: actions/checkout@v2
      - name: compile latex doc
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "./tex/*.tex"
          glob_root_file: true
      - name: deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: tex
  
